name: API Tests (Postman + Newman)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Newman
        run: npm i -g newman

      - name: Run Newman
        run: |
          newman run "postman/Mocktest API.postman_collection.json" \
            -e "postman/Mocktest.postman_environment.json" \
            --reporters cli,junit \
            --reporter-junit-export newman-report.xml

      - name: Upload test report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: newman-report
          path: newman-report.xml


